"""
REFLEX — Runbook Export Service
Export runbooks to Markdown and JSON formats.
Feature 13: Export to Markdown
"""

from datetime import datetime
from backend.models import Runbook, AnalysisResult, RunbookStep


def step_to_md(step: RunbookStep) -> str:
    """Convert a single runbook step to Markdown."""
    lines = []
    
    # Header with time and access
    meta = []
    if step.estimated_time:
        meta.append(f"⏱ {step.estimated_time}")
    if step.access_required:
        meta.append(f"🔑 {step.access_required}")
    meta_str = f" ({', '.join(meta)})" if meta else ""
    
    lines.append(f"**Step {step.order}**{meta_str}")
    lines.append(f"")
    lines.append(f"{step.action}")
    
    if step.command:
        lines.append("")
        lines.append("```bash")
        lines.append(step.command)
        lines.append("```")
    
    if step.expected_output:
        lines.append(f"")
        lines.append(f"✅ **Expected:** {step.expected_output}")
    
    if step.warning:
        lines.append(f"")
        lines.append(f"⚠️ **Warning:** {step.warning}")
    
    lines.append("")
    return "\n".join(lines)


def runbook_to_markdown(runbook: Runbook) -> str:
    """Convert a single runbook to a full Markdown document."""
    lines = []
    s = runbook.scenario
    
    # Header
    lines.append(f"# 🚨 {s.title}")
    lines.append("")
    lines.append(f"> **Severity:** {s.severity.upper()} | **Category:** {s.category} | **On-Call Level:** {runbook.on_call_level} | **Est. Resolution:** {runbook.estimated_resolution}")
    lines.append("")
    
    # Scenario details
    lines.append("## Overview")
    lines.append("")
    lines.append(f"**What:** {s.description}")
    lines.append("")
    lines.append(f"**Trigger:** {s.trigger}")
    lines.append("")
    lines.append(f"**Impact:** {s.impact}")
    lines.append("")
    lines.append(f"**Affected Code:** `{s.affected_code}`")
    lines.append("")
    lines.append(f"**Likelihood:** {s.likelihood}")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Detection
    lines.append("## 🔍 Detection")
    lines.append("")
    lines.append("How to confirm this incident is happening:")
    lines.append("")
    for step in runbook.detection:
        lines.append(step_to_md(step))
    lines.append("---")
    lines.append("")
    
    # Diagnosis
    lines.append("## 🔬 Diagnosis")
    lines.append("")
    lines.append("How to find the root cause:")
    lines.append("")
    for step in runbook.diagnosis:
        lines.append(step_to_md(step))
    lines.append("---")
    lines.append("")
    
    # Fix
    lines.append("## 🔧 Fix / Mitigate")
    lines.append("")
    lines.append("How to resolve the issue:")
    lines.append("")
    for step in runbook.fix:
        lines.append(step_to_md(step))
    lines.append("---")
    lines.append("")
    
    # Rollback
    lines.append("## ⏪ Rollback")
    lines.append("")
    lines.append("If the fix makes things worse:")
    lines.append("")
    for step in runbook.rollback:
        lines.append(step_to_md(step))
    lines.append("---")
    lines.append("")
    
    # Prevention
    lines.append("## 🛡️ Long-term Prevention")
    lines.append("")
    for i, p in enumerate(runbook.prevention, 1):
        lines.append(f"{i}. {p}")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Footer
    lines.append(f"*Generated by REFLEX on {datetime.now().strftime('%Y-%m-%d %H:%M')} — AI Incident Runbook Generator*")
    
    return "\n".join(lines)


def analysis_to_markdown(result: AnalysisResult) -> str:
    """Convert a full analysis result to a Markdown report."""
    lines = []
    
    # Title
    lines.append(f"# ⚡ REFLEX Analysis Report — {result.service_name}")
    lines.append("")
    lines.append(f"> **Overall Risk:** {result.overall_risk.upper()} | **Files Analyzed:** {result.files_analyzed} | **Scenarios Found:** {len(result.scenarios)} | **Runbooks Generated:** {len(result.runbooks)}")
    lines.append("")
    lines.append(f"**Summary:** {result.summary}")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Scenarios table
    lines.append("## Failure Scenarios")
    lines.append("")
    lines.append("| ID | Title | Severity | Category | Likelihood |")
    lines.append("|---|---|---|---|---|")
    for s in result.scenarios:
        sev_icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(s.severity, "⚪")
        lines.append(f"| {s.id} | {s.title} | {sev_icon} {s.severity} | {s.category} | {s.likelihood} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Dependencies
    lines.append("## Dependency Graph")
    lines.append("")
    lines.append("| Node | Type | Failure Modes |")
    lines.append("|---|---|---|")
    for n in result.dependency_graph.nodes:
        modes = ", ".join(n.failure_modes) if n.failure_modes else "—"
        lines.append(f"| {n.name} | {n.type} | {modes} |")
    lines.append("")
    lines.append("### Connections")
    lines.append("")
    for e in result.dependency_graph.edges:
        lines.append(f"- `{e.source}` → `{e.target}` ({e.relationship})")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # All runbooks
    for rb in result.runbooks:
        lines.append(runbook_to_markdown(rb))
        lines.append("")
        lines.append("---")
        lines.append("")
    
    # Footer
    lines.append(f"*Generated by REFLEX on {result.generated_at.strftime('%Y-%m-%d %H:%M')} — Powered by Mistral AI + Rust WASM*")
    
    return "\n".join(lines)
